### ISSUE TITLE
Looking for Source Code to Contribute

### ISSUE THREAD

**Issue by darrena092** [JvanKatwijk/unoPlugins-jan#8]
Hi there,

I've noticed that your project is licensed under GPL V2, but I couldn't find the source code in the repository. I'm interested in contributing to the project and would really appreciate it if you could point me to where the source code is available.

Thanks!

**Comment by JvanKatwijk** [comment]
The sources are in separate repositories, de folder with the doll's is just
for convenience


Op vr 1 sep. 2023 2:08 p.m. schreef Darren Anderson <
***@***.***>:

**Comment by darrena092** [comment]
Ah perfect, thanks!
